module.exports = {
    extends: [
        'standard',
    ],
    plugins: [
        'unicorn',
    ],
    rules: {
        'array-callback-return': [2, { allowImplicit: true }],
        'array-element-newline': [2, 'consistent'],
        'arrow-body-style': [2, 'as-needed', {
            requireReturnForObjectLiteral: false,
        }],
        'arrow-parens': [2, 'always', {
            requireForBlockBody: true,
        }],
        'arrow-spacing': [2, { before: true, after: true }],
        'brace-style': [2, '1tbs', { allowSingleLine: false }],
        'comma-dangle': [2, {
            arrays: 'always-multiline',
            objects: 'always-multiline',
            imports: 'always-multiline',
            exports: 'always-multiline',
            functions: 'always-multiline',
        }],
        complexity: [2, { max: 45 }],
        curly: [2, 'all'],
        'func-style': [2, 'expression'],
        'function-paren-newline': [2, 'consistent'],
        'import/exports-last': 2,
        'import/extensions': [2, 'never', { svg: 'always', worker: 'always', json: 'always', scss: 'always' }],
        'import/no-self-import': 2,
        'import/no-unused-modules': 2,
        'import/no-useless-path-segments': 2,
        indent: [2, 4, {
            SwitchCase: 1,
            VariableDeclarator: 1,
            outerIIFEBody: 1,
            MemberExpression: 1,
            FunctionDeclaration: { parameters: 1, body: 1 },
            FunctionExpression: { parameters: 1, body: 1 },
            CallExpression: { arguments: 1 },
            ArrayExpression: 1,
            ObjectExpression: 1,
            ImportDeclaration: 1,
            flatTernaryExpressions: false,
            ignoreComments: false,
        }],
        'keyword-spacing': 2,
        'linebreak-style': [2, 'unix'],
        'max-classes-per-file': [2, 2],
        'max-depth': 2,
        'max-len': [2, { code: 140, ignoreComments: true }],
        'max-nested-callbacks': 2,
        'max-statements-per-line': 2,
        'multiline-ternary': 0,
        'no-alert': 2,
        'no-console': 1,
        'no-const-assign': 2,
        'no-duplicate-imports': 2,
        'no-else-return': 2,
        'no-empty': 0,
        'no-eq-null': 2,
        'no-extra-semi': 2,
        'no-irregular-whitespace': 2,
        'no-lonely-if': 2,
        'no-loop-func': 2,
        'no-mixed-requires': 2,
        'no-multi-assign': 2,
        'no-multi-spaces': 2,
        'no-multiple-empty-lines': [2, { max: 1, maxEOF: 0, maxBOF: 0 }],
        'no-script-url': 2,
        'no-useless-concat': 2,
        'no-var': 2,
        'object-curly-spacing': [2, 'always'],
        'object-shorthand': [2, 'always'],
        'operator-assignment': [2, 'always'],
        'padding-line-between-statements': [
            2,
            { blankLine: 'always', prev: ['const', 'let', 'var', 'if'], next: '*' },
            { blankLine: 'always', prev: '*', next: ['if', 'return'] },
            { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] },
            { blankLine: 'always', prev: ['import', 'cjs-import'], next: '*' },
            { blankLine: 'always', prev: '*', next: ['import', 'cjs-import'] },
            {
                blankLine: 'any',
                prev: ['import', 'cjs-import'],
                next: ['import', 'cjs-import'],
            },
        ],
        'prefer-arrow-callback': [2, {
            allowNamedFunctions: false,
            allowUnboundThis: true,
        }],
        'prefer-const': [2, {
            destructuring: 'any',
            ignoreReadBeforeAssign: true,
        }],
        'prefer-numeric-literals': 2,
        'prefer-spread': 2,
        'prefer-template': 2,
        'promise/no-return-wrap': 2,
        'promise/valid-params': 2,
        'quote-props': [2, 'as-needed', { keywords: false, unnecessary: true, numbers: false }],
        'require-await': 2,
        'require-yield': 2,
        semi: [2, 'always'],
        'semi-style': [2, 'last'],
        'switch-colon-spacing': 2,
        'template-tag-spacing': [2, 'never'],
        'unicorn/catch-error-name': 2,
        'unicorn/error-message': 2,
        'unicorn/escape-case': 2,
        'unicorn/expiring-todo-comments': 2,
        'unicorn/filename-case': [2, {
            cases: {
                camelCase: true,
                pascalCase: true,
            },
            ignore: [
                /^[A-Z]+\.js$/,
                /^[A-Z]+\.[a-z]+\.?js$/,
                /^[a-z]+([A-Z][a-z]+)*[A-Z]+\.?js$/,
            ],
        }],
        'unicorn/new-for-builtins': 2,
        'unicorn/no-abusive-eslint-disable': 2,
        'unicorn/no-array-instanceof': 2,
        'unicorn/no-console-spaces': 2,
        'unicorn/no-hex-escape': 2,
        'no-nested-ternary': 0,
        'unicorn/no-nested-ternary': 2,
        'unicorn/no-new-buffer': 2,
        'unicorn/no-unreadable-array-destructuring': 2,
        'unicorn/no-unused-properties': 2,
        'unicorn/no-zero-fractions': 2,
        'unicorn/number-literal-case': 2,
        'unicorn/prefer-dataset': 2,
        'unicorn/prefer-event-key': 2,
        'unicorn/prefer-negative-index': 2,
        'unicorn/prefer-node-remove': 2,
        'unicorn/prefer-spread': 2,
        'unicorn/prefer-string-slice': 2,
        'unicorn/prefer-text-content': 2,
        'unicorn/prefer-type-error': 2,
        'unicorn/regex-shorthand': 2,
        'unicorn/throw-new-error': 2,
    },
};
