module.exports = {
    extends: [
        'plugin:json/recommended',
    ],
    plugins: [
        'react',
        'react-hooks',
    ],
    parserOptions: {
        ecmaFeatures: {
            jsx: true,
        },
    },
    settings: {
        react: {
            pragma: 'h',
        },
    },
    rules: {
        'jsx-quotes': [2, 'prefer-double'],
        'react/forbid-dom-props': [2, { forbid: ['className'] }],
        'react/jsx-boolean-value': 2,
        'react/jsx-closing-bracket-location': [2, 'line-aligned'],
        'react/jsx-closing-tag-location': 2,
        'react/jsx-curly-brace-presence': [2, { props: 'never', children: 'never' }],
        'react/jsx-curly-newline': [2, {
            multiline: 'require',
            singleline: 'consistent',
        }],
        'react/jsx-curly-spacing': [2, { when: 'never', children: { when: 'always' } }],
        'react/jsx-equals-spacing': [2, 'never'],
        'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
        'react/jsx-first-prop-new-line': [2, 'multiline-multiprop'],
        'react/jsx-indent': [2, 4, { indentLogicalExpressions: true }],
        'react/jsx-indent-props': [2, 4],
        'react/jsx-max-depth': [2, { max: 10 }],
        'react/jsx-max-props-per-line': [2, { when: 'multiline' }],
        'react/jsx-no-bind': [2, {
            allowArrowFunctions: true,
            allowBind: false,
            ignoreRefs: true,
        }],
        'react/jsx-no-comment-textnodes': 2,
        'react/jsx-no-duplicate-props': 2,
        'react/jsx-no-script-url': 2,
        'react/jsx-no-target-blank': [2, { allowReferrer: true }],
        'react/jsx-no-undef': 2,
        'react/jsx-no-useless-fragment': 2,
        'react/jsx-pascal-case': [2, { ignore: ['GTM', 'default'] }],
        'react/jsx-tag-spacing': [2, { beforeSelfClosing: 'always', beforeClosing: 'never' }],
        'react/jsx-uses-react': 2,
        'react/jsx-uses-vars': 2,
        'react/jsx-wrap-multilines': [2, {
            declaration: 'parens-new-line',
            assignment: 'parens-new-line',
            return: 'parens-new-line',
            arrow: 'parens-new-line',
            condition: 'parens-new-line',
            logical: 'parens-new-line',
        }],
        'react/no-access-state-in-setstate': 2,
        'react/no-array-index-key': 2,
        'react/no-children-prop': 2,
        'react/no-danger-with-children': 2,
        'react/no-did-update-set-state': 2,
        'react/no-direct-mutation-state': 2,
        'react/no-find-dom-node': 2,
        'react/no-is-mounted': 2,
        'react/no-render-return-value': 2,
        'react/no-string-refs': 2,
        'react/no-this-in-sfc': 2,
        'react/no-typos': 2,
        'react/no-unescaped-entities': 2,
        'react/no-will-update-set-state': 2,
        'react/prefer-stateless-function': 2,
        'react/react-in-jsx-scope': 0,
        'react/require-render-return': 2,
        'react/self-closing-comp': 2,
        'react/state-in-constructor': 2,
        'react-hooks/rules-of-hooks': 2,
    },
};
